# Multilingual support
LANGUAGES = {
    "my": {
        "welcome": "🙏 NexaMint Store မှ နွေးထွေးစွာကြိုဆိုပါတယ် ခင်ဗျာ!\nကျေးဇူးပြု၍ ဘော်ဒါ့ရဲ့နာမည်ကို ထည့်သွင်းပါ",
        "lang_select": "ဘာသာစကား ရွေးချယ်ပါ:",
        "main_menu": "မင်္ဂလာပါ {}! မည်သည့်ဝန်ဆောင်မှုကို လိုချင်ပါသလဲ?",
        "enter_mlbb": "ဘော်ဒါ့ရဲ့ Mobile Legends ID နှင့် Zone ကို ပြထားသလိုပုံစံနဲ့ ထည့်သွင်းပေးပါ:\n123456789 (1234)",
        "invalid_mlbb": "❌ ID/Zone ပုံစံမှားယွင်းနေပါသည်! ဥပမာ: 123456789 (1234)",
        "diamond_category": "ပုံမှန် Diamond\nအပတ်စဉ် Weekly Pass\nဘောနပ်စ် 2× double diamond:",
        "choose_package": "Diamond ပမာဏရွေးချယ်ပါ:",
        "price": "စျေးနှုန်း: {} MMK",
        "upload_payment": "ကျေးဇူးပြု၍ ငွေလွှဲ Screenshot တင်ပါ\n\nKBZPay - 09978772558 MZK\nUabPay - 09978772558 MZK\nWavePay - 09978772558 SYW\nAYAPay - 09978772558 SYW/nငွေမလွှဲခင် Updateဈေးများကို @NexaMint Channelမှာ သွားရောက်စစ်‌ဆေးပေးပါ",
        "wrong_screenshot": "❌ KBZPay သို့မဟုတ် WavePay screenshot သာလက်ခံပါသည်!",
        "order_confirm": "အော်ဒါအသေးစိတ်:\n\nID: {}\nဒိုင်းမွန်: {}\nစျေးနှုန်း: {} MMK\n\nအတည်ပြုပါမည်လား?",
        "order_success": "✅ အော်ဒါတင်ပြီးပါပြီ! အော်ဒါအခြေအနေကို /checkorder ဖြင့် စစ်ဆေးနိုင်ပါသည်။",
        "no_orders": "❌ သင့်မှာ မှာယူမှုမရှိသေးပါ",
        "order_details": "အော်ဒါ ID: {}\nအခြေအနေ: {}\nဒိုင်းမွန်: {}\nစျေးနှုန်း: {} MMK\nရက်စွဲ: {}",
        "help_text": "အကူအညီလိုပါက အက်ဒ်မင်နှင့် ဆက်သွယ်ပါ: @NexaMintSupport\n\nအမေးများသောမေးခွန်းများ:\nQ: ငွေလွှဲပြီးပါက ဒိုင်းမွန်ရရှိရန် ဘယ်လောက်ကြာမလဲ?\nA: မ်ိနစ်ပိုင်းအတွင်း အမြန်ဆုံးရရှိနိုင်ပါတယ်\n\nQ: ငွေလွှဲနည်း?\nA:\nKBZPay - 09978772558 MZK\nUabPay - 09978772558 MZK\nWavePay - 09978772558 SYW\nAYAPay - 09978772558 SYW\nငွေမလွှဲခင် Updateဈေးများကို @NexaMint Channelမှာ သွားရောက်စစ်‌ဆေးပေးပါ",
        "admin_notification": "🆕 အသစ်မှာယူမှု!\n\nအသုံးပြုသူ: {}\nအော်ဒါ ID: {}\nMLBB ID: {}\nဒိုင်းမွန်: {}\nစျေးနှုန်း: {} MMK",
        "order_not_found": "❌ အော်ဒါ ID မတွေ့ပါ",
        "order_completed": "✅ အော်ဒါ {} ပြီးစီးပါပြီ",
        "order_rejected": "❌ အော်ဒါ {} ပယ်ဖျက်ပြီး\nအကြောင်းပြချက်: {}",
        "pending_orders": "⏳ ဆိုင်းငံ့အော်ဒါများ:",
        "reject_reason": "ကျေးဇူးပြု၍ အော်ဒါပယ်ဖျက်ရသည့် အကြောင်းရင်းကို ထည့်သွင်းပါ:",
        "invalid_category": "❌ မမှန်ကန်သော ဒိုင်းမွန်အမျိုးအစား",
        "category_regular": "ပုံမှန်",
        "category_weekly": "အပတ်စဉ်",
        "category_bonus": "ဘောနပ်စ် diamondနှစ်ဆ"
    },
    "en": {
        "welcome": "🙏 Welcome to NexaMint!\nPlease enter your name:",
        "lang_select": "Choose your language:",
        "main_menu": "Hello {}! What service do you need today?",
        "enter_mlbb": "Please enter your Mobile Legends ID and Zone in this format:\n123456789 (1234)",
        "invalid_mlbb": "❌ Invalid ID/Zone format! Example: 123456789 (1234)",
        "diamond_category": "Choose diamond category:",
        "choose_package": "Choose diamond package:",
        "price": "Price: {} MMK",
        "upload_payment": "Please upload KBZPay, WavePay, UabPay, AYAPay payment screenshot\n\nKBZPay - 09978772558 MZK\nUabPay - 09978772558 MZK\nWavePay - 09978772558 SYW\nAYAPay - 09978772558 SYW",
        "wrong_screenshot": "❌ Only KBZPay or WavePay screenshots accepted!",
        "order_confirm": "Order Details:\n\nID: {}\nDiamonds: {}\nPrice: {} MMK\n\nConfirm order?",
        "order_success": "✅ Order placed successfully! Track status with /checkorder",
        "no_orders": "❌ You have no orders yet",
        "order_details": "Order ID: {}\nStatus: {}\nDiamonds: {}\nPrice: {} MMK\nDate: {}",
        "help_text": "Contact admin for help: @NexaMintSupport\n\nFAQ:\nQ: Delivery time after payment?\nA: can be delivered in a few minutes\n\nQ: Payment methods?\nA:\nKBZPay - 09978772558 MZK\nUabPay - 09978772558 MZK\nWavePay - 09978772558 SYW\nAYAPay - 09978772558 SYW",
        "admin_notification": "🆕 New Order!\n\nUser: {}\nOrder ID: {}\nMLBB ID: {}\nDiamonds: {}\nPrice: {} MMK",
        "order_not_found": "❌ Order ID not found",
        "order_completed": "✅ Order {} completed",
        "order_rejected": "❌ Order {} rejected\nReason: {}",
        "pending_orders": "⏳ Pending Orders:",
        "reject_reason": "Please enter reason for rejection:",
        "invalid_category": "❌ Invalid diamond category",
        "category_regular": "Regular",
        "category_weekly": "Weekly Pass",
        "category_bonus": "Bonus"
    }
}
